dist: trusty
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "rostykerei-github"
jdk:
  - oraclejdk8
script:
  - mvn clean site sonar:sonar codacy:coverage -DcoverageReportFile=target/site/jacoco/jacoco.xml
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'