dist: trusty
language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: "rostykerei-github"
jdk:
  - oraclejdk8
script:
  - mvn clean install sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'